apiVersion: v1
kind: ConfigMap
metadata:
  name: docapp
  namespace: chatbot
data:
  TEMPERATURE: "0.9"
  AZURE_OPENAI_BASE: https://dariuszopenai.openai.azure.com/
  AZURE_OPENAI_KEY: ""
  AZURE_OPENAI_TYPE: azure_ad
  AZURE_OPENAI_DEPLOYMENT: gpt-35-turbo-16k
  AZURE_OPENAI_MODEL: gpt-35-turbo-16k
  AZURE_OPENAI_ADA_DEPLOYMENT: text-embedding-ada-002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docapp
  labels:
    app: docapp
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: docapp
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: chatbot-sa
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: docapp
        image: dariuszregistry.azurecr.io/doc:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
        env:
        - name: TEMPERATURE
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: TEMPERATURE
        - name: AZURE_OPENAI_BASE
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: AZURE_OPENAI_BASE
        - name: AZURE_OPENAI_KEY
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: AZURE_OPENAI_KEY
        - name: AZURE_OPENAI_TYPE
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: AZURE_OPENAI_TYPE
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: AZURE_OPENAI_DEPLOYMENT
        - name: AZURE_OPENAI_MODEL
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: AZURE_OPENAI_MODEL
        - name: AZURE_OPENAI_ADA_DEPLOYMENT
          valueFrom:
            configMapKeyRef:
                name: docapp
                key: AZURE_OPENAI_ADA_DEPLOYMENT
---
apiVersion: v1
kind: Service
metadata:
  name: docapp
  labels:
    app: docapp
  namespace: chatbot
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: docapp
  type: LoadBalancer


  
